repository: M96s/siguso
repository_url: https://github.com/Mr96s/siguso

timezone: Asia/Shanghai
lang: zh_CN

title: 思谷搜 · Siguso.com | 全能高效的搜索导航,大航海时代的藏宝图
alias_en: Siguso
alias_cn: 思谷搜
description: 全能高效的搜索导航,大航海时代的藏宝图
keywords: 思谷导航, 思谷搜,思谷学术,siguso,导航网站,搜索导航
url: https://siguso.com
established_at: "2016-10-01T00:00+08:00"

author: Mr96
author_url: https://Mr96s.com
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]Mr96s[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
